#!/usr/bin/bash

mkdir -p ./doc/
mkdir -p ./doc/figs/
rm -r ./doc/figs/*


echo "Running Hydro1D..."
./bin/Hydro1D
echo

echo "Running plotting scripts..."
python src/plot/plot_hydrostatic.py
python src/plot/plot_output.py
echo

echo "Complete."
