#!/usr/bin/bash

mkdir -p ./doc/
mkdir -p ./doc/figs/

echo "Calculating polytropic solution to Lane-Emden..."
./bin/laneemden
python ./src/fileToIP.py
rm ./output/poly3
echo

echo "Interpolating Lane-Emden result..."
python ./src/interpolate.py
echo

echo "Running Hydro1D..."
./bin/Hydro1D
echo

echo "Running plotting script (may take some time)..."
python plot.py
echo

echo "Complete."
