#!/usr/bin/bash

mkdir -p ./doc/
mkdir -p ./doc/figs/
rm -r ./doc/figs/*


echo "Interpolating Lane-Emden result..."
python ./src/interpolate.py
echo

echo "Running Hydro1D..."
./bin/Hydro1D
echo

echo "Running plotting script..."
python plot.py
echo

echo "Complete."
